version: "3.9"

networks:
  laravel_project_one:
  project_two_laravel_project_one:
    external: true

services:
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8082:80
      # - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - redis

    container_name: laravel_project_one_server
    networks:
      - laravel_project_one
      - project_two_laravel_project_one
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php_laravel_project_one
    networks:
      - laravel_project_one
      - project_two_laravel_project_one
  redis:
    image: redis:alpine
    container_name: redis_laravel_project_one
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel_project_one
    command: redis-server --appendonly yes --replica-read-only no

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel_project_one
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_project_one

